config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#home'
  get 'top', to: 'home#top'
  get 'mypage', to: 'home#mypage'

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    unlocks: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users

  get '/api/v1/users/:id', to: 'api/v1/users#show'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/_footer.html.slim
footer
  .container
    .footer.center
      .footer-copyright
        = link_to "https://github.com/MoneyForest/", target: :_blank do
          i.fas.fa-copyright
          | 2020 @MoneyForest

app/views/layouts/_header.html.slim
nav.white
  .nav-wrapper
    .container
      ul#nav-mobile.hide-on-med-and-down
        .left
          li
            = link_to root_path, class: "scale-transition" do
              |
              i.fas.fa-home
        .right
          = render 'layouts/header/dropdown'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RailsBoilerplate
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, maximum-scale=1.0"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body id=("page-#{controller_path.gsub(%r([/_]), '-')}") class=("page-#{action_name}")
    = render "layouts/header"
    main
      .container.center
        - if notice
          p.notice= notice
        - if alert
          p.alert= alert
      = yield
    = render "layouts/footer"